# Generated by Django 5.0.1 on 2024-03-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCuerpoTecnico', '0002_ayudantecampo_entrenadorarqueros_kinesiologo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayudantecampo',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='directortecnico',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='entrenadorarqueros',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='kinesiologo',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='preparadorfisico',
            old_name='apeliido',
            new_name='apellido',
        ),
    ]
